### ISSUE TITLE
How to separate View from Fragment

### ISSUE THREAD

**Issue by TKolbusz** [TwistedEquations/android-rxmvp-tutorial#1]
Hi,

I love your code example, I wanted to develop separated design where View is separated from Fragment.
In activity it's easy, you inject View and setContentView() to that view. In fragment it's messed up because view is created on onCreateView(). Is there any way to implement that design to Fragment?

**Comment by patrick-doyle** [comment]
the onCreateView() method returns a view so instead of inflating a view you just return the inject/created one.
